version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://coupon_user:SecurePass123@postgres:5432/coupon_db
    depends_on:
      - postgres

  postgres:
    image: postgres:17.4.1
    environment:
      POSTGRES_USER: coupon_user
      POSTGRES_PASSWORD: SecurePass123
      POSTGRES_DB: coupon_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: